apiVersion: v2
name: cp-search
description: Cloud Pipeline search service (cp-search-srv), Elasticsearch (cp-search-elk), and curator
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: lib
    version: "1.0.0"
    repository: "file://../lib"
