apiVersion: v2
name: cp-notifier
description: Cloud-Pipeline email notifier (Deployment + cp-config-global patch)
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: lib
    version: "1.0.0"
    repository: "file://../lib"
