{{- if and .Values.enabled .Values.shareSrv.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cp-share-srv-fed-metadata-secret
  namespace: {{ include "lib.application.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  cp-share-srv-fed-meta.xml: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cp-hook-script-fetch-share-fed-meta
  namespace: {{ include "lib.application.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "6"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  fetch-share-fed-meta.sh: |
{{ .Files.Get "files/hooks/fetch-share-fed-meta.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hook-fetch-share-fed-meta
  namespace: {{ include "lib.application.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "7"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 600
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      serviceAccountName: {{ include "lib.hook.serviceaccount" . }}
      restartPolicy: Never
      containers:
        - name: hook-fetch-share-fed-meta
          image: {{ include "lib.hook.deploymentImage" . | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: {{ include "lib.application.namespace" . | quote }}
            - name: CP_IDP_INTERNAL_HOST
              value: {{ .Values.service.host.internal | quote }}
            - name: CP_IDP_INTERNAL_PORT
              value: {{ .Values.service.port.internal | quote }}
            - name: CP_IDP_EXTERNAL_HOST
              value: {{ .Values.service.host.external | quote }}
            - name: CP_IDP_EXTERNAL_PORT
              value: {{ .Values.service.port.external | quote }}
          command: ["/bin/bash", "/scripts/fetch-share-fed-meta.sh"]
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: cp-hook-script-fetch-share-fed-meta
            defaultMode: 0755
{{- end }}
