{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cp-hook-script-register-app-in-idp
  namespace: {{ include "lib.application.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "9"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  fetch-fed-meta.sh: |
{{ .Files.Get "files/hooks/fetch-fed-meta.sh" | indent 4 }}
  register-in-idp.sh: |
{{ .Files.Get "files/hooks/register-in-idp.sh" | indent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hook-register-app-in-idp
  namespace: {{ include "lib.application.namespace" . }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 1800
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      serviceAccountName: {{ include "lib.hook.serviceaccount" . }}
      restartPolicy: Never
      containers:
        - name: hook-register-app-in-idp
          image: {{ include "lib.hook.deploymentImage" . | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: {{ include "lib.application.namespace" . | quote }}
            - name: API_SRV_HOST
              value: {{ .Values.apiSrv.service.host.external | quote }}
            - name: API_SRV_PORT
              value: {{ .Values.apiSrv.service.port.external | quote }}
          envFrom:
            - configMapRef:
                name: cp-config-global
          command:
            - /bin/bash
            - -c
            - /scripts/fetch-fed-meta.sh cp-api-srv && /scripts/register-in-idp.sh "https://${API_SRV_HOST}:${API_SRV_PORT}/pipeline/"
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: cp-hook-script-register-app-in-idp
            defaultMode: 0755
{{- end }}
