vpc_id            = ""
subnet_id         = ""
instance_type     = ""
security_group_id = ""
region            = ""
# cloud_pipeline_deployment_commit = "abc123..."  # pin to a specific commit; defaults to "main"