enabled: true
# buildVersion: ""  # overrides general.buildVersion for this release

service:
  name: cp-storage-lifecycle-service

image:
  repository: quay.io/lifescience/cloud-pipeline
  tag: storage-lifecycle-service
  # buildVersion: ""  # overrides general.buildVersion for this image
  pullPolicy: Always  # IfNotPresent | Always | Never

archive:
  startAt: "23:00"  # Time of day to run the archive job (HH:MM)

restore:
  startEach: "20"  # Interval in minutes between restore checks

logsHostPath: /opt/cp-sls/logs  # Node local path for log files

config:
  # S3 key prefix inside CP_PREF_STORAGE_SYSTEM_STORAGE_NAME where S3 Batch Operations job reports are stored.
  CP_PREF_STORAGE_LIFECYCLE_SERVICE_REPORT_BUCKET_PREFIX: "storage-lifecycle-service/tagging-job-reports"
