{{- if .Values.gitlabDb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: cp-gitlab-db
  namespace: {{ include "lib.application.namespace" . }}
  labels:
    cloud-pipeline/cp-gitlab-db: "true"
    cloud-pipeline/core-component: "Service"
spec:
  ports:
    - protocol: TCP
      port: {{ include "cp-git.gitlabDbServicePort" . }}
      targetPort: {{ .Values.gitlabDb.port }}
      name: postgresql
  selector:
    cloud-pipeline/cp-gitlab-db: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-gitlab-db
  namespace: {{ include "lib.application.namespace" . }}
  labels:
    cloud-pipeline/cp-gitlab-db: "true"
    cloud-pipeline/core-component: "Deployment"
spec:
  selector:
    matchLabels:
      cloud-pipeline/cp-gitlab-db: "true"
  replicas: 1
  template:
    metadata:
      labels:
        cloud-pipeline/cp-gitlab-db: "true"
        cloud-pipeline/core-component: "Deployment"
    spec:
      {{- include "lib.imagePullSecret" . | nindent 6 }}
      nodeSelector:
        cloud-pipeline/cp-gitlab-db: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: cp-gitlab-db
          image: "{{ .Values.gitlabDb.image }}:{{ include "cp-git.gitlabDbImageTag" . }}"
          imagePullPolicy: {{ .Values.gitlabDb.imagePullPolicy }}
          args:
            - --shared_buffers={{ include "cp-git.gitlabDbSharedBuffers" . }}
            - --max_connections={{ include "cp-git.gitlabDbMaxConnections" . }}
          ports:
            - containerPort: {{ .Values.gitlabDb.port }}
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: DB_EXTENSION
              value: pg_trgm
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gitlab-pgdata
            - mountPath: /dev/shm
              name: gitlab-dshm
          readinessProbe:
            tcpSocket:
              port: {{ .Values.gitlabDb.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.gitlabDb.port }}
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 4
      volumes:
        - name: gitlab-pgdata
          hostPath:
            path: {{ .Values.gitlabDb.dataHostPath }}
            type: DirectoryOrCreate
        - name: gitlab-dshm
          emptyDir:
            medium: Memory
{{- end }}
