{{- if .Values.enabled }}
{{- $namespace := include "lib.application.namespace" . -}}
{{- $service := .Values.service | default dict -}}
{{- $serviceHost := index $service "host" | default dict -}}
{{- $servicePort := index $service "port" | default dict -}}
{{- $internalHost := index $serviceHost "internal" | default "" | toString | trim -}}
{{- $externalHost := index $serviceHost "external" | default "" | toString | trim -}}
{{- $internalPort := index $servicePort "internal" | default "443" | toString | trim -}}
{{- $externalPort := index $servicePort "external" | default "443" | toString | trim -}}

{{- if and (ne $externalHost "") (or (eq $internalHost "") (contains ".svc.cluster.local" $internalHost)) -}}
{{- $internalHost = $externalHost -}}
{{- $internalPort = $externalPort -}}
{{- end -}}

{{- if eq $internalHost "" -}}
{{- $internalHost = printf "cp-git.%s.svc.cluster.local" $namespace -}}
{{- end -}}

{{- $config := .Values.config | default dict -}}
{{- $data := dict -}}

{{- range $key, $value := $config -}}
{{- $_ := set $data $key ($value | toString) -}}
{{- end -}}

{{- $_ := set $data "GITLAB_DATABASE_HOST" (printf "cp-gitlab-db.%s.svc.cluster.local" $namespace) -}}
{{- $_ := set $data "GITLAB_HOST" (printf "cp-git.%s.svc.cluster.local" $namespace) -}}
{{- $_ := set $data "CP_GITLAB_EXTERNAL_HOST" $externalHost -}}
{{- $_ := set $data "CP_GITLAB_EXTERNAL_PORT" $externalPort -}}
{{- $_ := set $data "CP_GITLAB_INTERNAL_HOST" $internalHost -}}
{{- $_ := set $data "CP_GITLAB_INTERNAL_PORT" $internalPort -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-to-update-cp-git
  namespace: {{ include "lib.application.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
{{- range $key, $value := $data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{ include "lib.cpConfigGlobal.patchHookTemplate" (dict "context" . "hookWeight" "-7") }}
{{- end }}
