{{- $imageRef := "" -}}
{{- if hasPrefix "sha256:" .Values.nodeLogger.image.tag -}}
{{- $imageRef = printf "%s@%s" .Values.nodeLogger.image.repository .Values.nodeLogger.image.tag -}}
{{- else -}}
{{- $imageVersion := required "buildVersion must be set (set general.buildVersion in values.yaml. You also can override specific value with image.buildVersion value for each service pod)" (coalesce .Values.nodeLogger.image.buildVersion .Values.buildVersion "") -}}
{{- $imageRef = printf "%s:%s-%s" .Values.nodeLogger.image.repository .Values.nodeLogger.image.tag $imageVersion -}}
{{- end -}}
{{- if .Values.nodeLogger.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cp-node-logger
  namespace: {{ include "lib.application.namespace" . }}
  labels:
    cloud-pipeline/cp-node-logger: "true"
    cloud-pipeline/core-component: "DaemonSet"
spec:
  selector:
    matchLabels:
      cloud-pipeline/cp-node-logger: "true"
  template:
    metadata:
      annotations:
        deploy-timestamp: "{{ now | date "2006-01-02_15:04:05" }}"
      labels:
        cloud-pipeline/cp-node-logger: "true"
        cloud-pipeline/core-component: "DaemonSet"
    spec:
      {{- include "lib.imagePullSecret" . | nindent 6 }}
      containers:
        - name: cp-node-logger
          image: {{ $imageRef }}
          imagePullPolicy: {{ .Values.nodeLogger.image.pullPolicy }}
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: cp-config-global
          env:
            - name: CP_API_JWT_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "lib.cpApiTokenSecretName" . }}
                  key: CP_API_JWT_ADMIN
          volumeMounts:
            - name: kubelet-log
              mountPath: /var/log/kubelet
              readOnly: true
      volumes:
        - name: kubelet-log
          hostPath:
            path: /var/log/kubelet
{{- end }}
