apiVersion: v2
name: cp-run-policy-manager
description: Cloud-Pipeline run policy manager
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: lib
    version: "1.0.0"
    repository: "file://../lib"
