apiVersion: apps/v1
kind: Deployment
metadata:
  name: cp-notifier
  namespace: {{ include "lib.application.namespace" . }}
spec:
  selector:
    matchLabels:
      cloud-pipeline/cp-notifier: "true"
  replicas: 1
  template:
    metadata:
      annotations:
        deploy-timestamp: "{{ now | date "2006-01-02_15:04:05" }}"
      labels:
        cloud-pipeline/cp-notifier: "true"
        cloud-pipeline/core-component: "Deployment"
    spec:
      {{- include "lib.imagePullSecret" . | nindent 6 }}
      nodeSelector:
        cloud-pipeline/cp-notifier: "true"
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: cp-notifier
          {{- $imageVersion := required "buildVersion must be set (set general.buildVersion in values.yaml. You also can override specific value with image.buildVersion value for each service pod)" (coalesce .Values.image.buildVersion .Values.buildVersion "") }}
          {{- $imageRef := ternary (printf "%s@%s" .Values.image.repository .Values.image.tag) (printf "%s:%s-%s" .Values.image.repository .Values.image.tag $imageVersion) (hasPrefix "sha" .Values.image.tag) }}
          image: {{ $imageRef }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/init"]
          envFrom:
            - configMapRef:
                name: cp-config-global
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 4
          volumeMounts:
            - mountPath: /opt/notifier/logs
              name: notifier-logs
      volumes:
        - name: notifier-logs
          hostPath:
            path: /opt/notifier/logs
            type: DirectoryOrCreate
