{{- if eq (include "lib.imagePullSecretName" .) "cp-distr-docker-registry-secret" -}}
{{- $ipc := .Values.imagePullCredentials | default dict -}}
{{- $registry := index $ipc "registry" | default "https://index.docker.io/v1/" -}}
{{- $auth := printf "%s:%s" (index $ipc "user") (index $ipc "password") | b64enc -}}
{{- $dockerconfigjson := printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" $registry $auth | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: cp-distr-docker-registry-secret
  namespace: {{ include "lib.application.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson }}
{{- end }}
