apiVersion: v2
name: cp-billing-srv
description: Cloud Pipeline billing report agent (cp-billing-srv)
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: lib
    version: "1.0.0"
    repository: "file://../lib"
