apiVersion: v2
name: cp-git
description: Cloud Pipeline GitLab (cp-git) service
type: application
version: 0.1.0
appVersion: "latest"

dependencies:
  - name: lib
    version: "1.0.0"
    repository: "file://../lib"
